version: '2'
x-services:
  rails: &rails
    build: .
    environment:
      PGHOST: 'db'
      PGUSER: 'postgres'
    env_file:
      - .env
    volumes:
      - bundle:/usr/local/bundle
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app
    tty: true
    stdin_open: true
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql
  app:
    <<: *rails
    links:
      - db
    ports:
      - '3000:3000'
    command: "bash -c 'rm -rf tmp/pid/server.pid && rails s --binding 0.0.0.0'"
volumes:
  pgdata:
  bundle:
  node_modules:
